services:
  - type: web
    name: peerdrop-server
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm star
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        sync: false
